import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#f4f7f6',
    justifyContent: 'center',
    padding: 20,
  },
  scrollPage: {
    flexGrow: 1,
    backgroundColor: '#eef7f3',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 34,
  },
  brandBlock: {
    alignItems: 'center',
    marginBottom: 24,
  },
  logoFrame: {
    width: 86,
    height: 86,
    padding: 5,
    borderRadius: 26,
    backgroundColor: '#ffffff',
    shadowColor: '#07583f',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 7,
    marginBottom: 14,
  },
  logo: {
    width: '100%',
    height: '100%',
    borderRadius: 21,
  },
  brand: {
    color: '#12372f',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginBottom: 5,
  },
  subtitle: {
    color: '#60746c',
    fontSize: 14,
    fontWeight: '600',
  },
  form: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#e0ebe6',
    padding: 22,
    shadowColor: '#143d31',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.09,
    shadowRadius: 22,
    elevation: 6,
  },
  title: {
    color: '#173d31',
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  formSubtitle: {
    color: '#73857e',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 18,
  },
  modeSwitch: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 12,
    backgroundColor: '#eef4f1',
    marginBottom: 20,
  },
  modeOption: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 9,
  },
  modeOptionActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#173d31',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  modeText: {
    color: '#71837c',
    fontSize: 14,
    fontWeight: '700',
  },
  modeTextActive: {
    color: '#126b4d',
    fontWeight: '900',
  },
  fieldGroup: {
    marginBottom: 14,
  },
  label: {
    color: '#31463e',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  inputShell: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d7e3de',
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: '#f9fbfa',
  },
  input: {
    flex: 1,
    minHeight: 48,
    paddingHorizontal: 10,
    color: '#183e32',
    fontSize: 14,
  },
  textAreaShell: {
    alignItems: 'flex-start',
    paddingTop: 3,
  },
  textArea: {
    minHeight: 72,
    paddingTop: 13,
    textAlignVertical: 'top',
  },
  passwordToggle: {
    padding: 7,
    marginRight: -7,
  },
  button: {
    backgroundColor: '#117653',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 2,
    shadowColor: '#117653',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 9,
    elevation: 4,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  switchText: {
    color: '#657a72',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 18,
    textAlign: 'center',
  },
  switchAction: {
    color: '#126b4d',
    fontWeight: '900',
  },
  secureNote: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginTop: 18,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#edf2f0',
  },
  secureNoteText: {
    color: '#71837c',
    fontSize: 11,
    fontWeight: '600',
  },
  error: {
    color: '#8a1f1f',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 14,
    backgroundColor: '#fff2f1',
    borderRadius: 9,
    padding: 10,
  },
});
