import { StyleSheet } from 'react-native';

export const cartStyles = StyleSheet.create({
  page: {
    padding: 14,
    paddingBottom: 32,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    color: '#173d31',
    fontSize: 24,
    fontWeight: '800',
  },
  item: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dce7e2',
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    color: '#173d31',
    fontSize: 15,
    fontWeight: '800',
  },
  itemMeta: {
    color: '#657870',
    fontSize: 12,
    marginTop: 3,
  },
  itemPrice: {
    color: '#1a7f5a',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
  },
  qtyControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyButton: {
    width: 34,
    height: 34,
    borderRadius: 6,
    backgroundColor: '#e8f5ef',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyButtonText: {
    color: '#14543e',
    fontSize: 18,
    fontWeight: '800',
  },
  qtyText: {
    color: '#173d31',
    fontSize: 15,
    fontWeight: '800',
    minWidth: 22,
    textAlign: 'center',
  },
  deleteButton: {
    width: 34,
    height: 34,
    borderRadius: 6,
    backgroundColor: '#fff1f0',
    borderWidth: 1,
    borderColor: '#f4b4ad',
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalBox: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dce7e2',
    padding: 14,
    marginTop: 6,
    marginBottom: 12,
  },
  summaryRows: {
    gap: 9,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalLabel: {
    color: '#657870',
    fontSize: 14,
    fontWeight: '700',
  },
  totalValue: {
    color: '#173d31',
    fontSize: 18,
    fontWeight: '800',
  },
  summaryValue: {
    color: '#173d31',
    fontSize: 14,
    fontWeight: '800',
  },
  discountValue: {
    color: '#b42318',
    fontSize: 14,
    fontWeight: '800',
  },
  grandLabel: {
    color: '#173d31',
    fontSize: 15,
    fontWeight: '900',
  },
  primaryButton: {
    backgroundColor: '#1a7f5a',
    borderRadius: 6,
    paddingVertical: 13,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: '#e8f5ef',
    borderRadius: 6,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: '#14543e',
    fontSize: 13,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.55,
  },
  form: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dce7e2',
    padding: 14,
    marginBottom: 12,
  },
  label: {
    color: '#31463e',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: '#cddbd5',
    borderRadius: 6,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: '#ffffff',
  },
  textArea: {
    minHeight: 86,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
});
